name: Deploy theme to production moodle

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure you want to proceed? Type "yes" to confirm.'
        required: true
        default: 'no'

permissions:
  id-token: write
  contents: read

jobs:
  confirm-job:
    runs-on: ubuntu-latest
    environment: ProdApproval
    steps:
      - name: Check confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "yes" ]; then
            echo "Confirmation failed. Exiting workflow."
            exit 1
          fi
          echo "Confirmation successful. Proceeding..."

  copy_files:
    name: Copy files from github to Azure storage
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Copy files
        run: |
          find . -type f \
          -not -path "./.git/*" \
          -not -path "./.github/*" \
          -not -path "./.vs/*" \
          -not -name ".gitattributes" \
          -not -name ".gitignore" \
          -exec sh -c 'az storage file upload --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} --share-name ${{ vars.AZURE_FILE_SHARE }} --source {} --path nhse/${1#./}' _ '{}' --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \;
